### ISSUE TITLE
Strange output in `watch -n 2 kanban show`

### ISSUE THREAD

**Issue by lulivi** [coderofsalvation/kanban.bash#26]
## Description

Hello!
Firstly, great work here with this super cool script!

Secondly, I found that when I run the show command within a `watch`, it outputs a strange string at the end:

![image](https://user-images.githubusercontent.com/10894592/114521496-c31a7e00-9c42-11eb-819e-28c38db1be82.png)

This doesn't happen when I run `kanban show` without `watch` or when I run `watch` with another command:

![image](https://user-images.githubusercontent.com/10894592/114521830-1260ae80-9c43-11eb-8ffe-c2ffb690f5c4.png)

Any idea what can be happening here?

## Versions

bash: `5.1.0`

**Comment by YohananDiamond** [comment]
These are two escape codes: `ESC ? 12l` and `ESC ? 25h`
I'm not sure what `ESC ? 12l` does - and sadly I don't know where to look it up :/ , - but afaik `ESC ? 25h` means "show cursor".
Not sure what is causing them to appear, though. I'll try to take a look.

**Comment by coderofsalvation** [comment]
I'm checking this.
Currently I'm adding a `PLAIN=1` and `NOCOLOR=1` environment variable to support these kind of non-interactive usecases. 
Keep in touch!

**Comment by coderofsalvation** [comment]
> UPDATE: I found the issue! kanban and watch both clear the screen..
I've decided to remove the `clear` cmd inside kanban, because it's easy to just create an alias for it (`alias k="clear && kanban"` e.g.).

So the good news is that in the next version you'll be able to just type `watch NOCOLOR=1 kanban show` (watch doesn't like colors either). I'm still testing things but will merge it to master soon.
