### ISSUE TITLE
Terminal mode

### ISSUE THREAD

**Issue by marcus-downing** [coderofsalvation/kanban.bash#7]
When used in a normal terminal, `kanban show` uses ncurses commands to control the layout. But when used in a non-interactive terminal, this can have side effects.

An easy way to see this is to run:
```sh
$ watch kanban show
```

This will print spurious control characters: `^[H^[2J` before the list and `^[?12l^[?25h` after it. `kanban show` should attempt to detect the terminal mode to see whether or not to output layout control characters.

**Comment by coderofsalvation** [comment]
PR anyone (or maintainer-request anyone)?

**Comment by coderofsalvation** [comment]
Ok, I had a look at it:

There were indeed two occurences of weird chars.
It was the `clear` statement, which caused the top occurence, which i removed (also makes it less opiniated, since people can still add an alias k=`clear;kanban show` etc) 

The second one however, I couldn't figure out which caused it.
Anyways, with the latest version you can do this now:

```
watch -t './kanban show | head -n-1'
```

> NOTE: the head is needed to remove the footer-garbage
